### ISSUE TITLE
Could not update .ICEauthority file /home/user/.ICEauthority

### ISSUE THREAD

**Issue by Fenrilas** [linuxmint/lmde-3-cinnamon-beta#33] opened 2018-08-04 17:37 UTC
Yesterday I decided to update my kernel from 4.9 to 4.17.0.0 using the Debian backports. Everything went quite smoothly until I rebooted my pc. After logging in to Cinnamon, I only got a black screen, and a moment later an error message that said "could not update .ICEauthority file /home/user/.ICEauthority. The only option given was to log out. I looked all over the internet for a solution, but anything with chmod or chown didn't help. I found at least a temporary fix in installing XFCE through command line, which somehow was able to log in. From XFCE I could delete two files; .ICEauthority-n and .ICEauthority-c. After deleting these two files, I managed to boot into Cinnamon as well, with my kernel updated. However, after yesterday, booting into Cinnamon takes more than 10 seconds from the log in screen, which is a lot longer than it used to be. 

Additional information: I was unable to log in even using the old kernel or the recovery mode. Scouring the internet pointed to automatic login being the issue. I have it disabled now.

**Comment by xenopeek** [comment] 2018-08-05 14:57
I enabled automatic login, added the Stretch backports repository and then installed the 4.17 kernel from there (with: `sudo apt-get -t stretch-backports linux-image-amd64`). Rebooting my system the .ICEauthority issue doesn't happen.

Additionally I did some tests before and after and compared startup times (with: `systemd-analyze`). If I look at below I'd say the newer kernel starts up a bit slower—probably from new mitigation for Spectre/Meltdown variants—but I can't see that startup from the login screen (userspace) takes _a lot_ longer. Even with the same kernel and configuration startup time will vary a little between boots.
```
Startup finished in 2.515s (kernel) + 7.828s (userspace) = 10.344s [4.9 kernel, manual login]
Startup finished in 2.365s (kernel) + 7.688s (userspace) = 10.054s [4.9 kernel, auto login]
Startup finished in 2.921s (kernel) + 7.122s (userspace) = 10.044s [4.17 kernel, manual login]
Startup finished in 3.080s (kernel) + 7.956s (userspace) = 11.037s [4.17 kernel, auto login]
```
As I can't reproduce the .ICEauthority issue, the perceived slowdown, or relate either to the LMDE 3 beta with the steps you described I'm closing this issue.  You can take help from the [forums](https://forums.linuxmint.com/viewforum.php?f=246) with analyzing and troubleshooting the slower startup you experience.

**Closed as completed by xenopeek** 2018-08-05 14:57 UTC
