### ISSUE TITLE
ethernet not connecting

### ISSUE THREAD

**Issue by macglenn** [linuxmint/lmde-3-cinnamon-beta#60] opened 2018-08-17 20:17 UTC
ETHERNET NOT AUTO CONNECTING
I am running 3 beta off a usb.  I installed it from another usb using the live version.  The live version connected to the ethernet wired connection.  The actual install does not.  I haven't included any hardware info here because it doesn't seem relevant.
My problem solving. 1. copied all ethernet settings from working hard drive version of mint 18.3 and entered into 3 beta.  It still would try to log in but not succeed.
I removed the network app and tried entering the settings through the setup menu.
Still no auto login.  If I right click and disable networking and then re-enable it finally logs in.
So far, it happens every time.  
Everything else is fine so far
thanks
macglenn

**Comment by clefebvre** [comment] 2018-10-01 13:18
Closing as the cause wasn't found and the BETA is now finished.

**Closed as completed by clefebvre** 2018-10-01 13:18 UTC
