### ISSUE TITLE
Bluetooth paired but don't work with bluetooth device.

### ISSUE THREAD

**Issue by ghost** [linuxmint/lmde-3-cinnamon-beta#27] opened 2018-08-02 08:21 UTC
While listening to music by my bluetooth speaker paired well with Cindy, but It doesn't play in bluetooth speaker but play in laptop's speaker, altghough it is paired well with Cindy. 
Hence, It works well with Tara Cinnamon.

**Comment by clefebvre** [comment] 2018-08-05 08:16
Hi @bagjunggyu, if it's paired the BT side of things should be OK. It might be a sound device selection issue in Cinnamon then? Try to run "cinnamon-settings sound" from the terminal and see if you can spot issues in the terminal when selecting the BT speakers as the output.

**Comment by ghost** [comment] 2018-08-05 09:24
Hi @clefebvre 
In sound, it doesn't show me BT speaker sometimes, 
and in case of showing BT speaker, it drops frequently.
Let me show you my situation as video for two Oses Tara and Cindy showing differences between two OSes.
I hope it might help you to resolve it :)
After closing this issue, It will be removed from youtube.
Tara
https://youtu.be/0qMh_LfGMi4
Lmde 3
https://youtu.be/_67jdJjixUo
​
P.S) 
And, don't forget the missing translation for BT speaker sound in Cindy, Please
As you can see it in Tara.
Headset Head Unit (HSP/HFP)
High Fidelity Playback (A2DP Sink)

**Comment by ghost** [comment] 2018-08-06 00:41
@clefebvre Now, I have one 
Please, see this new recorded video 
https://youtu.be/kVBp317jPSQ

​and this is output

bagjunggyu@cindy:~$ cinnamon-settings sound
Using pam module (python3-pampy)
Loading Sound module

(cinnamon-settings.py:3182): Cvc-CRITICAL **: gvc_mixer_card_get_profile: assertion 'GVC_IS_MIXER_CARD (card)' failed

(cinnamon-settings.py:3182): Cvc-CRITICAL **: gvc_mixer_card_get_name: assertion 'GVC_IS_MIXER_CARD (card)' failed

(cinnamon-settings.py:3182): Cvc-CRITICAL **: gvc_mixer_card_change_profile: assertion 'GVC_IS_MIXER_CARD (card)' failed

**Comment by clefebvre** [comment] 2018-08-06 14:15
Hi @bagjunggyu,

I'm not sure what to say. Blueberry is the frontend to gnome-bluetooth and cinnamon-settings/sound is the frontend to pulseaudio. Both seem to be doing their job.

It's hard to say whether the issue is in the bluetooth connection (although it pairs successfully, maybe it advertises the wrong profiles, or maybe it disconnects abruptly), or in the pulseaudio configuration (which could be different in Ubuntu and Debian).

Either way it seems upstream to us. I'd suggest checking the system logs to see what pulseaudio and bluetooth say in detail, and then search upstream in Debian for relative bug reports.

If it's OK, I'll close this issue here as there's nothing much we can fix in blueberry/cinnamon.

**Comment by ghost** [comment] 2018-08-06 15:41
Thank you for your kind instruction :)
Happy to know what it comes from.
Thank you :)

**Closed as completed** 2018-08-06 21:40 UTC

**Comment by ghost** [comment] 2018-08-06 23:26
For the clue, this is ouput of /var/log/syslog
Aug  6 09:36:17 cindy bluetoothd[521]: Unknown seq type
Aug  6 09:36:20 cindy bluetoothd[521]: Unable to get Headset Voice gateway SDP record: Device or resource busy
Aug  6 09:36:20 cindy bluetoothd[521]: connect error: Device or resource busy (16)
Aug  6 09:36:21 cindy bluetoothd[521]: Unable to get Headset Voice gateway SDP record: Device or resource busy
Aug  6 09:36:21 cindy bluetoothd[521]: connect error: Device or resource busy (16)
Aug  6 09:36:22 cindy bluetoothd[521]: Unable to get Headset Voice gateway SDP record: Device or resource busy
Aug  6 09:36:22 cindy bluetoothd[521]: connect error: Device or resource busy (16)
Aug  6 09:36:23 cindy bluetoothd[521]: Unable to get Headset Voice gateway SDP record: Device or resource busy
Aug  6 09:36:23 cindy bluetoothd[521]: connect error: Device or resource busy (16)
Aug  6 09:36:23 cindy bluetoothd[521]: Unable to get Headset Voice gateway SDP record: Device or resource busy
Aug  6 09:36:23 cindy bluetoothd[521]: connect error: Device or resource busy (16)
Aug  6 09:36:24 cindy bluetoothd[521]: Unable to get Headset Voice gateway SDP record: Device or resource busy
Aug  6 09:36:24 cindy bluetoothd[521]: connect error: Device or resource busy (16)
Aug  6 09:36:29 cindy bluetoothd[521]: GLib: Source ID 550 was not found when attempting to remove it
Aug  6 09:36:29 cindy kernel: [ 1585.549864] input: F0:85:C1:9E:2C:6E as /devices/virtual/input/input27
Aug  6 09:36:32 cindy rtkit-daemon[559]: Supervising 3 threads of 1 processes of 1 users.
Aug  6 09:36:32 cindy rtkit-daemon[559]: Successfully made thread 2972 of process 1185 (n/a) owned by '1000' RT at priority 5.
Aug  6 09:36:32 cindy rtkit-daemon[559]: Supervising 4 threads of 1 processes of 1 users.
Aug  6 09:36:32 cindy kernel: [ 1588.471346] Bluetooth: hci0 SCO packet for unknown connection handle 0
Aug  6 09:36:32 cindy kernel: [ 1588.471351] Bluetooth: hci0 SCO packet for unknown connection handle 0
Aug  6 09:36:32 cindy kernel: [ 1588.471353] Bluetooth: hci0 SCO packet for unknown connection handle 0
Aug  6 09:36:34 cindy dbus-daemon[1004]: Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service'
Aug  6 09:36:34 cindy systemd[987]: Starting GNOME Terminal Server...
Aug  6 09:36:34 cindy dbus-daemon[1004]: Successfully activated service 'org.gnome.Terminal'
Aug  6 09:36:34 cindy systemd[987]: Started GNOME Terminal Server.
Aug  6 09:36:58 cindy bluetoothd[521]: Start: Connection timed out (110)
Aug  6 09:36:58 cindy pulseaudio[1185]: [pulseaudio] bluez5-util.c: Transport Acquire() failed for transport /org/bluez/hci0/dev_F0_85_C1_9E_2C_6E/fd0 (Input/output error)
Aug  6 09:36:59 cindy pulseaudio[1185]: [pulseaudio] backend-native.c: connect(): 장치나 자원이 동작 중
Aug  6 09:37:00 cindy bluetoothd[521]: Abort: Connection timed out (110)
Aug  6 09:37:00 cindy acpid: input device has been disconnected, fd 20
Aug  6 09:37:04 cindy pulseaudio[1185]: [pulseaudio] module-bluez5-device.c: Refused to switch profile to a2dp_sink: Not connected
Aug  6 09:37:09 cindy pulseaudio[1185]: [pulseaudio] backend-native.c: connect(): 장치나 자원이 동작 중
Aug  6 09:37:11 cindy pulseaudio[1185]: [pulseaudio] module-bluez5-device.c: Refused to switch profile to a2dp_sink: Not connected
Aug  6 09:37:12 cindy pulseaudio[1185]: [pulseaudio] backend-native.c: connect(): 장치나 자원이 동작 중
Aug  6 09:37:14 cindy pulseaudio[1185]: [pulseaudio] backend-native.c: connect(): 장치나 자원이 동작 중
Aug  6 09:37:16 cindy pulseaudio[1185]: [pulseaudio] module-bluez5-device.c: Refused to switch profile to a2dp_sink: Not connected
