### ISSUE TITLE
Does not recognize a LG 42LT75 TV when it is connected by HDMI

### ISSUE THREAD

**Issue by mdcll** [linuxmint/lmde-3-cinnamon-beta#66] opened 2018-08-30 08:20 UTC
When I connect my tv LG 42LT75 (42")by HDMI. It recognizes my TV like a gold star of 32". That means that i can't use the 1920 x 1080 screen configuration. The same installation it is recognized well by w10.

[configuracion pantalla.pdf](https://github.com/linuxmint/lmde-3-cinnamon-beta/files/2335255/configuracion.pantalla.pdf)
![captura de pantalla de 2018-08-30 08-53-06](https://user-images.githubusercontent.com/42099759/44838972-d321f280-ac3d-11e8-8c2f-68f066fc352b.png)

**Comment by clefebvre** [comment] 2018-10-01 13:20
This looks upstream to us. Check with xrandr that the modes provided are the same.

Closing as the cause wasn't found and the BETA is now finished.

**Closed as completed by clefebvre** 2018-10-01 13:20 UTC
