### ISSUE TITLE
Calamares Installer does not advise when to remove USB after install

### ISSUE THREAD

**Issue by ovari** [linuxmint/lmde-3-cinnamon-beta#36] opened 2018-08-05 02:12 UTC
Once LMDE 3 has been installed, could the Calamares Installer advise on when it is "save to remove the USB"? Thank you

**Comment by clefebvre** [comment] 2018-08-05 08:07
Duplicate of https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/28. This is done by a systemd job, it shouldn't matter which installer is used.

**Closed as completed by clefebvre** 2018-08-05 08:07 UTC
