### ISSUE TITLE
Boot fails after install

### ISSUE THREAD

**Issue by micha-silver** [linuxmint/lmde-3-cinnamon-beta#63] opened 2018-08-24 08:44 UTC
I tried to install LMDE 3 but the install process failed at the last step of "Configuring boot sector". The installation simply closed without showing the final "Installation complete" message and returned me to the Live system. My partition scheme included a 200MB efi partition, mounted on /boot/efi. 
Then when I rebooted, I was dropped to the grub prompt.

After several tries with the same result, I installed instead the regular Mint 19, with no issues whatsoever. Everything worked as expected (using the same partition scheme as the LMDE attempts)

Hardware is a 4 yr old HP laptop with 8MB RAM.

**Comment by micha-silver** [comment] 2018-08-24 09:27
![grub_error](https://user-images.githubusercontent.com/3841768/44782885-59342f80-ab91-11e8-9dec-563e5df7b236.jpg)
[live_install.log](https://github.com/linuxmint/lmde-3-cinnamon-beta/files/2331795/live_install.log)

I tried once again, Here's information with solution:
The status line messages at the end of the installation were
**Configuring bootloader
Checking bootloader
Cleaning Apt**   <<===Here the installer crashed

Then after reboot I get the grub prompt with "error: unknown filesystem"

I was able to get back to a bootable system with the instructions here: https://community.linuxmint.com/tutorial/view/245
Restart the Live system, mount the installed root directory and rerun sudo grub-install with required parameters.

Regards, Micha

EDIT:
Install log and a photo of the grub error screen are attached to this post

**Comment by ChrisM62** [comment] 2018-08-24 15:46
It sounds almost similar, but my experience is a little difference. 

I installed on a Lenovo P50, 32GB with 1 SDD (512GB), 1 HDD (512GB) and 1 SSD (512GB). It was running Debian 10 with the two SSD's tied together using LVM2. UEFI boot. 64bit, Debian was a multiarch. 

So I wanted to try and get LMDE 3 to install to a similar setup. Assuming it should be easy, as I went from Debian 9 to 10, and LMDE 3 is Debian 9 based, I expected easy installation. It was not.

I tried installing LMDE 3 on one SSD, tried to use LVM2, and in all cases the installer completed without an error, but the machine refused to boot. Nothing happened, no efi boot. I tried Debian 9, worked first try. I tried using the menus, tried the expert mode, all yielded the same result. No boot.

The one thing I did notice on LMDE 3 is that gparted kept telling me that the device wanted a 2048 alignment, but Linux insisted on 512. Unless I pressed ignore, I could not proceed. The Debian install was done using the graphical installation and I used their menus to partition and set up LVM, but never once saw that message. 

Because I tried to simply straight install on the first disk (sda, the 512GB SSD), I can rule out LVM being the problem. That one, where the installer did all the work, also yielded a non booting system. I tried fixing the efi partition, but only got messages on 32bit things, as I was using 64bit only, it didn't make sense and I didn't pursue that. 

Once difference I noticed was that LMDE3 when allowed to, installed /boot/efi, / and swap partition on disk 1, Debian 9 went for /boot/efi, /boot, / and swap. /boot/efi being FAT32, /boot being Ext2 and / Ext4. I tried to replicate this in the expert mode, but that didn't do the trick. 

Eventually I wanted to see if it would work once installed, so I thought of 2 options, one was to use Debian to partition, go to the LMDE 3 installer and get it use the Debian 9 prepared disk. I choose not to try that because I suspected it was a problem with filling /boot/efi correctly. So I installed Debian 9, then copied over the apt configuration from a VB client running LMDE 3 and used that. I then got the list of packages from the VB client, copied that over and simply installed all of those. The only adjustment I made was to include 64bit uefi stuff (grub and syslinux) and not the VB client choices there. I also added the Stretch-backports and upgraded the kernel and MATE to 1.20. 

That has almost worked, all but the grub menu visual became Cindy. The resulting system looks and behaves in line with the VB clients I've been testing with. It is stable, fast. But I would not want to repeat the installation. I think in total I tried in 6 different ways or so. I'll fix my grub visuals tonight and start restoring the personal stuff to see if all is well. Most of my documents and downloads are on the rotating disk, so they never got erased :) 

I would like to see the installer be more Debian like when you partition. Not just that I can easily set up a LVM 2 disk and use it as /, but also that the uefi stuff is handled better. I'm still not sure we need the /ext2 partition, but the debian approach does yield a boot with me. The debian installer sets the /boot/efi partition to 512MiB, and the /boot to 244MiB.

**Comment by micha-silver** [comment] 2018-08-24 18:57
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Thanks for the response.
    
    On 08/24/2018 06:46 PM, ChrisM62 wrote:
    
    
      
      It sounds almost similar, but my experience is a little
        difference.
      I installed on a Lenovo P50, 32GB with 1 SDD (512GB), 1 HDD
        (512GB) and 1 SSD (512GB). It was running Debian 10 with the two
        SSD's tied together using LVM2. UEFI boot. 64bit, Debian was a
        multiarch.
      So I wanted to try and get LMDE 3 to install to a similar
        setup. Assuming it should be easy, as I went from Debian 9 to
        10, and LMDE 3 is Debian 9 based, I expected easy installation.
        It was not.
      I tried installing LMDE 3 on one SSD, tried to use LVM2, and in
        all cases the installer completed without an error, but the
        machine refused to boot. Nothing happened, no efi boot. I tried
        Debian 9, worked first try. I tried using the menus, tried the
        expert mode, all yielded the same result. No boot.
      The one thing I did notice on LMDE 3 is that gparted kept
        telling me that the device wanted a 2048 alignment, but Linux
        insisted on 512. Unless I pressed ignore, I could not proceed.
        The Debian install was done using the graphical installation and
        I used their menus to partition and set up LVM, but never once
        saw that message.
    
    
    
    I also saw that message, and like you, I ignored it.
    
    
    
      Because I tried to simply straight install on the first disk
        (sda, the 512GB SSD), I can rule out LVM being the problem. That
        one, where the installer did all the work, also yielded a non
        booting system. I tried fixing the efi partition, but only got
        messages on 32bit things, as I was using 64bit only, it didn't
        make sense and I didn't pursue that.
    
    Isn't that because the efi partition is FAT32? So the software in
      that boot partition is 32 bit.
    
    
    
    
      Once difference I noticed was that LMDE3 when allowed to,
        installed /boot/efi, / and swap partition on disk 1, Debian 9
        went for /boot/efi, /boot, / and swap. /boot/efi being FAT32,
        /boot being Ext2 and / Ext4. I tried to replicate this in the
        expert mode, but that didn't do the trick.
    
    
    
    I did not use a separate boot partition. Only a 200MB partition,
      formatted as FAT32 and mounted on /boot/efi. Then only two other
      partitions, root and home, both formatted as ext4.
    
    
    
    
      Eventually I wanted to see if it would work once installed, so
        I thought of 2 options, one was to use Debian to partition, go
        to the LMDE 3 installer and get it use the Debian 9 prepared
        disk. I choose not to try that because I suspected it was a
        problem with filling /boot/efi correctly. So I installed Debian
        9, then copied over the apt configuration from a VB client
        running LMDE 3 and used that. I then got the list of packages
        from the VB client, copied that over and simply installed all of
        those. The only adjustment I made was to include 64bit uefi
        stuff (grub and syslinux) and not the VB client choices there. I
        also added the Stretch-backports and upgraded the kernel and
        MATE to 1.20.
      That has almost worked, all but the grub menu visual became
        Cindy. The resulting system looks and behaves in line with the
        VB clients I've been testing with. It is stable, fast. But I
        would not want to repeat the installation. I think in total I
        tried in 6 different ways or so. I'll fix my grub visuals
        tonight and start 
    
    
    
    I totally agree. Getting a bootable installation today should be
      trivial, even with all the complexities of UEFI. All the distros
      handle this smoothly, including Debian, so LMDE will get it worked
      out also, I'm sure. But the beta release, it seems, still has this
      boot sector issue.
    
    
    
    
      restoring the personal stuff to see if all is well. Most of my
        documents and downloads are on the rotating disk, so they never
        got erased :)
      I would like to see the installer be more Debian like when you
        partition. Not just that I can easily set up a LVM 2 disk and
        use it as /, but also that the uefi stuff is handled better. I'm
        still not sure we need the /ext2 partition, but the debian
        approach does yield a boot with me. The debian installer sets
        the /boot/efi partition to 512MiB, and the /boot to 244MiB.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linuxmint/lmde-3-cinnamon-beta","title":"linuxmint/lmde-3-cinnamon-beta","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/linuxmint/lmde-3-cinnamon-beta"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ChrisM62 in #63: It sounds almost similar, but my experience is a little difference. \r\n\r\nI installed on a Lenovo P50, 32GB with 1 SDD (512GB), 1 HDD (512GB) and 1 SSD (512GB). It was running Debian 10 with the two SSD's tied together using LVM2. UEFI boot. 64bit, Debian was a multiarch. \r\n\r\nSo I wanted to try and get LMDE 3 to install to a similar setup. Assuming it should be easy, as I went from Debian 9 to 10, and LMDE 3 is Debian 9 based, I expected easy installation. It was not.\r\n\r\nI tried installing LMDE 3 on one SSD, tried to use LVM2, and in all cases the installer completed without an error, but the machine refused to boot. Nothing happened, no efi boot. I tried Debian 9, worked first try. I tried using the menus, tried the expert mode, all yielded the same result. No boot.\r\n\r\nThe one thing I did notice on LMDE 3 is that gparted kept telling me that the device wanted a 2048 alignment, but Linux insisted on 512. Unless I pressed ignore, I could not proceed. The Debian install was done using the graphical installation and I used their menus to partition and set up LVM, but never once saw that message. \r\n\r\nBecause I tried to simply straight install on the first disk (sda, the 512GB SSD), I can rule out LVM being the problem. That one, where the installer did all the work, also yielded a non booting system. I tried fixing the efi partition, but only got messages on 32bit things, as I was using 64bit only, it didn't make sense and I didn't pursue that. \r\n\r\nOnce difference I noticed was that LMDE3 when allowed to, installed /boot/efi, / and swap partition on disk 1, Debian 9 went for /boot/efi, /boot, / and swap. /boot/efi being FAT32, /boot being Ext2 and / Ext4. I tried to replicate this in the expert mode, but that didn't do the trick. \r\n\r\nEventually I wanted to see if it would work once installed, so I thought of 2 options, one was to use Debian to partition, go to the LMDE 3 installer and get it use the Debian 9 prepared disk. I choose not to try that because I suspected it was a problem with filling /boot/efi correctly. So I installed Debian 9, then copied over the apt configuration from a VB client running LMDE 3 and used that. I then got the list of packages from the VB client, copied that over and simply installed all of those. The only adjustment I made was to include 64bit uefi stuff (grub and syslinux) and not the VB client choices there. I also added the Stretch-backports and upgraded the kernel and MATE to 1.20. \r\n\r\nThat has almost worked, all but the grub menu visual became Cindy. The resulting system looks and behaves in line with the VB clients I've been testing with. It is stable, fast. But I would not want to repeat the installation. I think in total I tried in 6 different ways or so. I'll fix my grub visuals tonight and start restoring the personal stuff to see if all is well. Most of my documents and downloads are on the rotating disk, so they never got erased :) \r\n\r\nI would like to see the installer be more Debian like when you partition. Not just that I can easily set up a LVM 2 disk and use it as /, but also that the uefi stuff is handled better. I'm still not sure we need the /ext2 partition, but the debian approach does yield a boot with me. The debian installer sets the /boot/efi partition to 512MiB, and the /boot to 244MiB. "}],"action":{"name":"View Issue","url":"https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63#issuecomment-415799709"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63#issuecomment-415799709",
"url": "https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63#issuecomment-415799709",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [linuxmint/lmde-3-cinnamon-beta] Boot fails after install (#63)",
"sections": [
{
"text": "",
"activityTitle": "**ChrisM62**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ChrisM62",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"linuxmint/lmde-3-cinnamon-beta\",\n\"issueId\": 63,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"linuxmint/lmde-3-cinnamon-beta\",\n\"issueId\": 63\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63#issuecomment-415799709"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 371975782\n}"
}
],
"themeColor": "26292E"
}
]
    
    
    -- 
Micha Silver
Arava Drainage Authority
cell: +972-523-665918

**Comment by clefebvre** [comment] 2018-08-28 10:03
Cleaning Apt <<===Here the installer crashed

We could probably fix that if you could get the error output (from the terminal, launching "sudo live-installer"). Hopefully this should output a Python exception.

**Comment by micha-silver** [comment] 2018-08-28 12:21
[live_install.log](https://github.com/linuxmint/lmde-3-cinnamon-beta/files/2331798/live_install.log)
![grub_error](https://user-images.githubusercontent.com/3841768/44783018-baf49980-ab91-11e8-85ef-925c5822974b.jpg)

  
    
    body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Hello Clem:
    I reinstalled, running live-installer from the terminal, and got the
    same grub error. Again the installer exited without the usual
    "Installation complete"  window. After the installation exited, I
    rebooted with the live USB and was again able to do grub-install to
    re-setup the booting.
    
    Here is the install log (copied from the terminal) as you suggested,
    and a photo of the computer screen showing the grub error. Hope this
    helps to find the problem.
    
    Regards,
    Micha
    
    On 08/28/2018 01:03 PM, Clement
      Lefebvre wrote:
    
    
      
      Cleaning Apt <<===Here the installer crashed
      We could probably fix that if you could get the error output
        (from the terminal, launching "sudo live-installer"). Hopefully
        this should output a Python exception.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linuxmint/lmde-3-cinnamon-beta","title":"linuxmint/lmde-3-cinnamon-beta","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/linuxmint/lmde-3-cinnamon-beta"}},"updates":{"snippets":[{"icon":"PERSON","message":"@clefebvre in #63: Cleaning Apt \u003c\u003c===Here the installer crashed\r\n\r\nWe could probably fix that if you could get the error output (from the terminal, launching \"sudo live-installer\"). Hopefully this should output a Python exception."}],"action":{"name":"View Issue","url":"https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63#issuecomment-416526164"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63#issuecomment-416526164",
"url": "https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63#issuecomment-416526164",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [linuxmint/lmde-3-cinnamon-beta] Boot fails after install (#63)",
"sections": [
{
"text": "",
"activityTitle": "**Clement Lefebvre**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@clefebvre",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"linuxmint/lmde-3-cinnamon-beta\",\n\"issueId\": 63,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"linuxmint/lmde-3-cinnamon-beta\",\n\"issueId\": 63\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63#issuecomment-416526164"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 371975782\n}"
}
],
"themeColor": "26292E"
}
]
    
    
    -- 
Micha Silver
Arava Drainage Authority
cell: +972-523-665918

**Comment by clefebvre** [comment] 2018-08-29 09:05
Hi Micha,

Your attachments didn't make it to Github. Can you add them directly at https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/63?

**Comment by clefebvre** [comment] 2018-08-29 09:06
You can also "apt update" and "apt install live-installer" from the live session to grab the latest installer... we've fixed many things since the BETA.

**Comment by micha-silver** [comment] 2018-08-29 10:46
I've attached to log and grub screen to the post above.
Cheers, Micha

**Comment by micha-silver** [comment] 2018-08-29 10:47
Will there be a "BETA2" ??

**Comment by clefebvre** [comment] 2018-08-29 23:38
The log looks ok, I can't see any crash in it. There was a race condition in the BETA which resulted in the installer sometimes exiting before showing the end dialog, this was fixed in the updated installer.

There won't be another BETA.

**Comment by micha-silver** [comment] 2018-08-30 12:08
And yet the installer consistently left the computer unbootable. As I mentioned, after installation completed I was able to boot again into the live system with the installation USB, then reset grub. And after that everything works fine. (Same laptop with regular Debian and previously with Mint 18 installed and booted fine...)
Thanks

**Comment by clefebvre** [comment] 2018-10-01 13:19
Closing as the cause wasn't found and the BETA is now finished.

**Closed as completed** 2018-10-01 13:19 UTC
